exec-once = hypridle &
exec-once = /usr/bin/hyprsunset --temperature 6000
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = waypaper --fill fill --wallpaper "$(find ~/hyprland-dotfiles/wallpapers -type f | shuf -n 1)"
exec-once = /usr/bin/waypaper --fill fill --wallpaper $HOME/hyprland-dotfiles/wallpapers/dusk.png
exec-once = /usr/bin/waybar
exec-once = /usr/bin/dunst
exec-once = /usr/bin/fcitx5 -d
#exec-once = systemctl --user start hyprpolkitagent
#exec-once = systemctl --user enable --now hypridle.service
#exec-once = qs -c noctalia-shell
