# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Fix dragging issues with XWayland
# windowrule = noinitialfocus, class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

### CUSTOM ###
# 'sys-info' floating terminal
windowrule = match:float true, match:class ^(sys-info)$
windowrule = center true, match:class ^(sys-info)$
windowrule = size 1100 700, match:class ^(sys-info)$

# 'netmenu' floating window
windowrule = match:float true, match:class ^(netmenu)$
windowrule = center true, match:class ^(netmenu)$
windowrule = size 700 500, match:class ^(netmenu)$

# 'sys-monitor' floating terminal
windowrule = match:float true, match:class ^(sys-monitor)$
windowrule = center true, match:class ^(sys-monitor)$
windowrule = size 1200 750, match:class ^(sys-monitor)$
