#$text_color = rgba(FFDAD6FF)
#$entry_background_color = rgba(41000311)
#$entry_border_color = rgba(896E6C55)
#$entry_color = rgba(FFDAD6FF)
#$font_family = Rubik Light
#$font_family_clock = Rubik Light
#$font_material_symbols = Material Symbols Rounded

# Text (soft cream)
$text_color = rgba(FFF5EEFF)

# Entry fill (light translucent pink)
$entry_background_color = rgba(FFB7C533)

# Entry border (rose)
$entry_border_color = rgba(EA8BAA88)

# Text inside entry
$entry_color = rgba(FFF5EEFF)

# Optional darker overlay accent
$overlay_color = rgba(00000025)
